### ISSUE TITLE
Fails when running node app.js

### ISSUE THREAD

**Issue by hdsouza** [DanDev95/bypasser#17]
Hi, 
Thanks for the code. I completed all the instruction and when I run the node app.js, It opens a browser, navigates to the close , then closes it down with the error below:
I copied your 3 files from your website and use them as is.
(url used = https://democaptcha.com/demo-form-eng/hcaptcha.html)
How can we fix this?
Thanks.

PS C:\Temp\Youtube> node app.js
Solving Captcha...
file:///C:/Temp/Youtube/bypass/captchaBypasser.js:11
      async (err, [, captchaKey]) => {
      ^

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))      
    at file:///C:/Temp/Youtube/bypass/captchaBypasser.js:11:7
    at PythonShell._endCallback (C:\Temp\Youtube\node_modules\python-shell\index.js:254:20)
    at terminateIfNeeded (C:\Temp\Youtube\node_modules\python-shell\index.js:209:39)       
    at ChildProcess.<anonymous> (C:\Temp\Youtube\node_modules\python-shell\index.js:182:13)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

**Comment by hdsouza** [comment]
The error is now gone. Not sure how though.
I am able to use the script and  get 2captcha to solve correctly, although the free version does not work for me.
In the free version, the right check appears, but if you click on the continue button to go to the next page it says Captcha required.

**Comment by Kiriox94** [comment]
Hello I have the same problem did you finally find how you solved the problem?
